lemaire:
    resource: "@LemaireBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /tests
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
     
contact_form:
    path:     /infos
    defaults: { _controller: LemaireBundle:Default:contact }
    